id="explorer-merger"
description="A tool to converts new Explorer windows into tabs."
version="1.1.0"
author="Wu Junkai"
github="https://github.com/WuJunkai2004"
license="MIT"
include="windhawk.exe"
compilerOptions="-lole32 -loleaut32 -lshell32 -luser32 -luuid"